parameters:
  apihelper.security.default_provider: 'main'
  apihelper.security.requirements.login: ~
  apihelper.security.requirements.connect: ~
  apihelper.security.requirements.callback: ~
  apihelper.security.options: []

services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Alhames\ApiHelperBundle\Core\ServiceManager: ~

  Alhames\ApiHelperBundle\Security\Core\Authentication\Provider\OAuthProvider:
    abstract: true

  apihelper.manager: '@Alhames\ApiHelperBundle\Core\ServiceManager'
  apihelper.security.authentication.provider: '@Alhames\ApiHelperBundle\Security\Core\Authentication\Provider\OAuthProvider'

  Alhames\ApiHelperBundle\Controller\ServiceController:
    arguments:
      $options: '%apihelper.security.options%'
      $httpUtils: '@security.http_utils'
    public: true
    tags: ['controller.service_arguments']
