services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Alhames\ApiHelperBundle\Core\ServiceManager: ~

  Alhames\ApiHelperBundle\Security\Http\Firewall\OAuthListener:
    parent: 'security.authentication.listener.abstract'
    abstract: true

  Alhames\ApiHelperBundle\Security\Core\Authentication\Provider\OAuthProvider:
    abstract: true

  Alhames\ApiHelperBundle\Core\CaptchaManager: ~

  Alhames\ApiHelperBundle\EventListener\CaptchaSubscriber:
    abstract: ture

  apihelper.manager: '@Alhames\ApiHelperBundle\Core\ServiceManager'
  apihelper.security.authentication.listener: '@Alhames\ApiHelperBundle\Security\Http\Firewall\OAuthListener'
  apihelper.security.authentication.provider: '@Alhames\ApiHelperBundle\Security\Core\Authentication\Provider\OAuthProvider'

  apihelper.security.authentication.listener.captcha: '@Alhames\ApiHelperBundle\EventListener\CaptchaSubscriber'

  Alhames\ApiHelperBundle\Controller\ServiceController:
    arguments:
      $options: '%apihelper.security.options%'
    public: true
    tags: ['controller.service_arguments']

#<?xml version="1.0" ?>
#
#<container xmlns="http://symfony.com/schema/dic/services"
#           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
#           xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd">
#    <services>
#        <service id="apihelper.manager" class="%apihelper.manager.class%">
#            <argument type="collection"/>
#        </service>
#
#        <service id="apihelper.security.authentication.listener"
#                 class="%apihelper.security.authentication.listener.class%"
#                 parent="security.authentication.listener.abstract"
#                 public="false"
#                 abstract="true"/>
#
#        <service id="apihelper.security.authentication.provider"
#                 class="%apihelper.security.authentication.provider.class%"
#                 public="false"
#                 abstract="true">
#            <argument /> <!-- User Provider -->
#            <argument /> <!-- User Checker -->
#            <argument /> <!-- Provider-shared Key -->
#            <argument type="service" id="apihelper.manager"/>
#        </service>
#
#        <service id="apihelper.captcha.manager.abstract"
#                 class="%apihelper.captcha.manager.class%"
#                 abstract="true"/>
#
#        <service id="apihelper.security.authentication.listener.captcha"
#                 class="%apihelper.captcha.subscriber.class%"
#                 abstract="true">
#            <argument type="service" id="security.http_utils"/>
#            <argument type="service" id="apihelper.captcha.manager"/>
#            <argument type="service" id="request_stack"/>
#            <argument/><!-- Options -->
#            <argument/><!-- Authentication Failure Handler -->
#        </service>
#    </services>
#</container>
